stages:
  - Merge
  - Live
Merge:
  stage: Merge
  script:
    # - export
    # - whoami

    # # View changes and remove .git
    - sudo rm -rf .git
    - sudo rm -rf src
    - sudo rm -rf .babelrc
    - sudo rm -rf postcss.config.js
    - sudo rm -rf webpack.config
    # - sudo rm -rf sass/
    - sudo rm -rf package-lock.json
    - sudo rm -rf package.json
    # - sudo rm -rf tempcss/
    - sudo ls -l
    # - sudo rm -rf .sass-cache
  artifacts:
    untracked: true
    name: "$CI_PROJECT_NAME"
    paths:
      - ./
Deploy:
  stage: Live
  when: on_success
  script:
    # Replace with latest build
    - sudo rm -rf /var/www/tamerelsayed.com/root/css
    - sudo rm -rf /var/www/tamerelsayed.com/root/images
    - sudo rm -rf /var/www/tamerelsayed.com/root/index.html
    - sudo cp -a * /var/www/tamerelsayed.com/root/
    - sudo chmod -R 777 /home/gitlab-runner/builds